print("what is ur name")
nameUser = input()
print("How pld r u?")
ageUser = input()
print("Where r u live?")
cityUser = input()
print("This is {0}.".format(nameUser))
print("It is {0}.".format(ageUser))
print("(S)He live in {0}.".format(cityUser))